apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: {{ .Values.vmName }}-network
  namespace: {{ .Values.namespace | default "default" }}
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
